jwt-const:
  issuer: green@green.kr #?? ???
  secret: ad123f1654q8aw869afa5a3w51gea4bh7a148a65qwr65q1ad32f1
  header-schema-name: Authorization
  claim-key: signedUser
  token-type: Bearer
  token-name: JWT
  access-token-expiry: 600_000 # 10? ms
  refresh-token-expiry: 1_296_000_000 # 15? ms
  refresh-token-cookie-name: refresh-token
  refresh-token-cookie-expiry: 1_296_000 #15? s
file:
  directory: D:\Students\jang jin seong\download\greengram_ver3
mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/jwt
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true